# SPDX-License-Identifier: GPL-2.0-only
# Copyright (c) 2026 farfromoffice

# The CI actions are tracked.
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions:
        patterns: ["*"]
    commit-message:
      prefix: ci
