#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-2.0-only
# Copyright (c) 2026 farfromoffice

"""Turns an app icon into the pixels the desktop can blit.

Icons are kept as SVG next to the app that owns them, because that is the form
they are edited in. The kernel has no vector rasteriser and is not getting one,
so the shape is rasterised here and the result is committed.

Run it when an icon changes. The build does not depend on it.
"""

import argparse
import subprocess
import sys
import tempfile
from pathlib import Path

from PIL import Image


def rasterise(source, size):
    with tempfile.TemporaryDirectory() as workspace:
        png = Path(workspace) / "icon.png"

        subprocess.run(
            [
                "magick",
                "-background",
                "none",
                "-density",
                "384",
                str(source),
                "-resize",
                f"{size}x{size}",
                f"PNG32:{png}",
            ],
            check=True,
            capture_output=True,
        )

        return Image.open(png).convert("RGBA").copy()


def emit(name, image, source, out):
    width, height = image.size
    pixels = image.tobytes()

    print("// SPDX-License-Identifier: GPL-2.0-only", file=out)
    print("// Copyright (c) 2026 farfromoffice", file=out)
    print(file=out)
    print(f"// Generated by scripts/gen-icon.py from {source}, do not edit.", file=out)
    print(file=out)
    print("#include <eris/types.hpp>", file=out)
    print(file=out)
    print("namespace eris::modules {", file=out)
    print(file=out)
    print(f"extern const u16 {name}_width = {width};", file=out)
    print(f"extern const u16 {name}_height = {height};", file=out)
    print(file=out)
    print(f"extern const u8 {name}_pixels[] = {{", file=out)

    for start in range(0, len(pixels), 24):
        chunk = pixels[start:start + 24]
        print("    " + " ".join(f"{value}," for value in chunk), file=out)

    print("};", file=out)
    print(file=out)
    print("} // namespace eris::modules", file=out)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--svg", required=True, help="the icon to rasterise")
    parser.add_argument("--size", type=int, default=48, help="pixels on a side")
    parser.add_argument("--name", required=True, help="name of the generated symbols")
    parser.add_argument("--out", required=True, help="where to write the source")
    arguments = parser.parse_args()

    image = rasterise(Path(arguments.svg), arguments.size)

    with open(arguments.out, "w", encoding="utf-8") as out:
        emit(arguments.name, image, Path(arguments.svg).name, out)

    print(f"{arguments.out}: {image.size[0]} by {image.size[1]}", file=sys.stderr)


if __name__ == "__main__":
    main()
