#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-2.0-only
# Copyright (c) 2026 farfromoffice
set -euo pipefail

# Turns the function symbols of a linked image into a table the kernel can read
# at panic time. Run against the first link pass, compiled into the second.

image=${1:-}

{
    echo "// SPDX-License-Identifier: GPL-2.0-only"
    echo "// Generated by scripts/gen-ksyms.sh, do not edit."
    echo
    echo "#include <eris/ksyms.hpp>"
    echo
    echo "namespace eris {"
    echo
    echo "extern const KsymEntry ksyms_table[];"
    echo "extern const usize ksyms_table_count;"
    echo
    echo "const KsymEntry ksyms_table[] = {"

    if [[ -n $image && -f $image ]]; then
        nm --numeric-sort --defined-only --demangle "$image" \
            | awk '$2 ~ /^[tTwW]$/ { name = $3; for (i = 4; i <= NF; i++) name = name " " $i;
                                     gsub(/\\/, "\\\\", name); gsub(/"/, "\\\"", name);
                                     printf "    { 0x%s, \"%s\" },\n", $1, name }'
    fi

    echo "};"
    echo
    echo "const usize ksyms_table_count = sizeof(ksyms_table) / sizeof(ksyms_table[0]);"
    echo
    echo "} // namespace eris"
}
